### ISSUE TITLE
--self-test option

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#37] opened 2015-05-23 15:56 UTC
given the enormous number of tests in the suite, having it be able to test each test would be good. (and getting to where all the tests would actually run, good also, predefined defaults for more servers, etc)

so either the --self-test thing could be embedded in flent (using localhost? or a set of predefined servers on the internet?) or run from an external driver script parsing --list-tests.

**Comment by tohojo** [comment] 2015-05-23 15:59
Agreed. However, also a duplicate of #25 as far as I'm concerned. :)

**Closed** 2015-05-23 15:59 UTC
Labels: duplicate
