### ISSUE TITLE
setting cong control via --test-parameters

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#64] opened 2016-05-05 04:01 UTC
I've had this fragment of a thought sitting in my tree for ages. Since we seem to always be getting comparisons from reno, I kind of wanted a simple way to change any given test to use reno (and other cong control algorithms), and note that very visibly in the test...

```
## -*- mode: python; coding: utf-8 -*-

# Mixin include file to change congestion control algorithms

# Fixme - figure out how to put this in the meta data
# to change the label name dynamically when doing comparison tests
# Teach find_netperf about it
#      {'command': find_netperf("TCP_STREAM", LENGTH, HOSTS[1],
#   marking=DSCP,
#                               extra_test_args=EXTRA_TEST_ARGS),
# How can you change the window inside a program?
# (would be useful for rsync/torrents using tcp)


CC_UP=TEST_PARAMETERS.get('cc_up')
CC_DOWN=TEST_PARAMETERS.get('cc_down')
CC=TEST_PARAMETERS.get('cc')
CC_WIN=TEST_PARAMETERS.get('cc_window')

if CC:
   EXTRA_TEST_ARGS="-K "+CC+","+CC
if CC_UP and CC_DOWN:
   EXTRA_TEST_ARGS="-K "+CC_UP+","+CC_DOWN
   else:
   if CC_UP
   # Not sure about syntax here
      EXTRA_TEST_ARGS="-K "+CC_UP
      else:
      EXTRA_TEST_ARGS="-K ","+CC_DOWN
```

**Comment by tohojo** [comment] 2017-09-15 12:23
Duplicate of #35

**Closed by tohojo** 2017-09-15 12:23 UTC
